services:
  postgres:
    image: 'postgres:15-alpine'
    environment:
      - 'POSTGRES_DB=devsu_bank_db'
      - 'POSTGRES_PASSWORD=5ecret'
      - 'POSTGRES_USER=devsu_oe'
    ports:
      - '5432:5432'
